logto-io/go

core/generator.go
core/generator_test.go

feat(core): generator functions
UT Passed.

feat(core): generator functions

---

core/sign_in.go
core/sign_in_test.go
core/sign_out.go
core/sign_out_test.go

feat(core): generate sign in & sign out URI
UT Passed.

feat(core): generate sign in & sign out uri

---

core/fetch_token.go
core/fetch_token_test.go
core/go.mod
core/go.sum
core/oidc_config.go
core/oidc_config_test.go
core/parse_response.go
core/revoke.go
core/revoke_test.go

feat(core): core fetch functions
* fetchOidcConfig
* fetchTokenByAuthorizationCode
* fetchTokenByRefreshToken
* revoke
UTs passed.

feat(core): core functions to interact with OIDC APIs

---

core/errors.go
core/verify_and_parse_code_from_callback_uri.go
core/verify_and_parse_code_from_callback_uri_test.go

feat(core): `verifyAndParseCodeFromCallbackUri`
UT passed.

feat(core): `verifyAndParseCodeFromCallbackUri`

---

.github/workflows/main.yml

ci: lint and run unit tests
None.

ci: lint and run unit tests

---

client/client.go
client/go.mod
client/go.sum
client/handle_sign_in_callback.go
client/helper.go
client/session_storage.go
client/sign_in.go
client/storage.go
client/util.go
core/fetch_jwks.go
core/fetch_token.go
core/fetch_token_test.go
go.work
go.work.sum

* Add `FetchJwks` in core
* Make the props of `FetchTokenByAuthorizationCodeOptions` public for they are used in the client package
Test locally in web sample.

feat: logto client

---

client/sign_out.go
core/revoke.go
core/revoke_test.go

feat(client): handle signing out
* Make props of the `RevocationOptions` public for they're used in the client package.
Test locally in web sample.

feat(client): handle signing out

---

client/client.go
client/go.mod
client/go.sum
client/handle_sign_in_callback.go
client/helper.go
client/util.go
core/fetch_token.go
core/fetch_token_test.go
go.work.sum

* GetIdTokenClaims
* GetAccessToken
* Change `HandleSignInCallback` to receive an `http.Request` parameter for a more smooth SDK API usage.
* Export `AccessToken` props, for we need to store it in the storage in JSON format.
* Export `FetchTokenByRefreshTokenOptions` for we will use them in the client package.
Test locally in web sample.

feat: add authenticated user related method

---

core/fetch_jwks_test.go

test(core): fetchJwks

---

.github/workflows/main.yml
client/util_test.go

- add UTs for utils in the client package
- run the client UT and upload the client UT report
Tested by CI.

test(client): util

---

client/client.go
client/helper.go
client/helper_test.go
go.mod
go.sum

rebase master and replace `logto_access_token_map` key with constant `StorageKeyAccessTokenMap`
test(client): client helper
UT

test(client): client helper

---

client/client_test.go

test(client): `GetAccessToken`
UT

test(client): `GetAccessToken`

---

client/client.go
client/errors.go
client/sign_out.go

refactor(client): extract errors
UT

refactor(client): extract errors

---

client/handle_sign_in_callback_test.go

test(client): handle sign in callback
UT

test(client): handle sign in callback

---

.github/workflows/main.yml
client/sign_in_test.go

* test(client): sign in
* add `-gcflags=all=-l` in test command, for the mock util need to [disable inlining](https://github.com/agiledragon/gomonkey#notes).
UT

test(client): sign in

---

client/sign_out_test.go

test(client): sign out

---

client/handle_sign_in_callback.go

refactor(client): replace sign-in context key with constant value `StorageKeySignInContext`
UT

refactor(client): replace sign-in context key with constant value

---

client/client_test.go
client/handle_sign_in_callback_test.go
client/helper_test.go
client/sign_in_test.go
client/sign_out_test.go
client/util_test.go
core/decode_id_token_test.go
core/fetch_jwks_test.go
core/fetch_token_test.go
core/generator_test.go
core/oidc_config_test.go
core/revoke_test.go
core/sign_in_test.go
core/sign_out_test.go
core/verify_and_parse_code_from_callback_uri_test.go
core/verify_id_token_test.go
go.mod
go.sum

refactor: use `assert` in test cases
UT

refactor: use `assert` in test cases

---

client/constants.go
client/handle_sign_in_callback.go
client/handle_sign_in_callback_test.go
client/sign_in.go
client/sign_in_test.go

rename `SignInContext` -> `SignInSession` to align with other traditional web app SDKs.
UT

refactor(client): rename `SignInContext` -> `SignInSession`

---

.github/workflows/release.yml

ci: run release workflow on tag pushed
CI

ci: run release workflow only on tag pushed

---

.github/workflows/main.yml

Run the main workflow on `push-action` branches before they're merged into `master`.

ci: run main workflow on `push-action` branches

---

client/client.go
gin-sample/main.go

feat(client): persist access tokens all the time
UT

feat(client): persist access tokens all the time

---

.github/workflows/publish.yml

The `git-chglog` will update the change log according to a version tag, so we need to tag the release commit before generating the change log, otherwise the change log will not be updated.
Test locally.

ci: generate the change log after the commit is tagged

---

client/client.go
client/client_test.go
core/constants.go
core/fetch_user_info.go
core/fetch_user_info_test.go
core/oidc_config_test.go
core/sign_in.go
core/type.go

- feat: fetch user info
- extract preserved scopes and define user scopes
UT

feat: fetch user info

---

client/client.go

Remove the parameter scope for getAccessTokenByRefreshToken. Then the OP server will automatically attach all the available scopes (in refresh token) to this access token.
Test locally.

feat(client): remove scope for access token grant

---

core/decode_id_token_test.go
core/fetch_user_info_test.go
core/type.go
core/verify_id_token_test.go

refactor(core): remove deprecated role names
UT

refactor(core): remove deprecated role names

---

client/sign_out.go
core/sign_out.go
core/sign_out_test.go

replace `idTokenHint` with `clientId` in sign-out url
UT & Test locally.

refactor(core): replace `idTokenHint` with `clientId` in sign-out url

---

README.md

chore: fix document link

---

client/client.go

should pass in resource props when calling FetchTokenByRefreshToken 
We can get the correct access token:
OR

fix(client): add resource when calling FetchTokenByRefreshToken

---

.chglog/config.yml
CHANGELOG.md

Only `feat`, `fix`, `perf`, `refactor`, and `chore` are allowed in the change log.
Tested locally.
OR

chore: the change log should only contain specific commit types

---

client/client.go
client/client_test.go
core/fetch_user_info.go
core/fetch_user_info_test.go
gin-sample/main.go

We should use the access token to fetch user information.
UT & Test locally.
OR

fix: fetch user info

---

README.md

chore: update doc links for readme
Test locally.
OR

chore: update doc links for readme

---

core/type.go

feat(core): add organization data to userinfo response
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~

feat(core): add organization data to userinfo response

---

.github/workflows/commitlint.yml

revert: revert "chore: always run commit lint"

---

core/fetch_user_info_test.go
core/type.go

Add missing `roles`, `organizations` and `organization roles` fields for user info response data.
Test locally and UT added.

feat: add roles and organiaztion-related data for `userInfoResponse`

---

README.md

refactor: update SDK tutorial link
Test locally.

refactor: update SDK tutorial link

---

.github/workflows/commitlint.yml

Fix commitlint CI, since the `@commitlint/config-conventional` package has became a ESM module, so we need to update the config file accordingly.
CI
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~

ci: fix commitlint ci

---

.gitignore
gin-sample/.env.example
gin-sample/compose.yml
gin-sample/main.go

Fix a zero missing in host and add compose file to run anywhere to test.
Closes #107

fix: correct hostname for gin sample and add compose file to run anywhere to test

---

.github/workflows/publish.yml

ci: update publish action
No need.
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~

ci: update publish action

---

gin-sample/main.go

chore: update sample deps
No need.
~~- [ ] `.changeset`~~
~~- [ ] unit tests~~
~~- [ ] integration tests~~
~~- [ ] necessary TSDoc comments~~

chore: update sample deps
